### ISSUE TITLE
Add RStudio version

### ISSUE THREAD

**Issue by thisisnic** [forwards/first-contributions#7]
"New branch" doesn't appear in RStudio if you have an earlier version of RStudio.  Confirmed as 1.0.143 from Apr 2017 having this issue but need to work out which version (and add this to instructions).  Maybe add it in a "troubleshooting" section?

**Comment by Jcolebeyond02** [comment]
Troubleshoot

**Comment by thisisnic** [comment]
Closing this issue as stale
